### ISSUE TITLE
Passing Functions

### ISSUE THREAD

**Issue by lccodes** [IdentityPython/JWTConnect-Python-CryptoJWT#1]
https://github.com/IdentityPython/cryptojwt/blob/c271e19bab3561b631f05f3299b48ca181eb8c07/src/cryptojwt/jwk.py#L390

Is cryptojwt still under construction to a certain extent?

**Comment by rohe** [comment]
I don't know what you mean with under construction. 
All the open source software I've ever dealt with has all been under construction.
But if you mean if it's ready to be used, then my answer would be yes.

**Comment by jschlyter** [comment]
It was a Base class that @lccodes pointed to, hence the `pass` is correct.
