### ISSUE TITLE
Why JWS converts "typ" header claim name in "type"

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/JWTConnect-Python-CryptoJWT#126]
Here https://github.com/IdentityPython/JWTConnect-Python-CryptoJWT/blob/main/src/cryptojwt/jws/jws.py#L119

When I need a typ value it converts automatically this claim name to type

it should be typ instead
https://datatracker.ietf.org/doc/html/rfc7519#section-5.1

is this an implementation typo?

**Comment by rohe** [comment]
yes

**Comment by peppelinux** [comment]
Ok, let's merge the pending PRs and have a new release :-)
https://github.com/IdentityPython/JWTConnect-Python-CryptoJWT/pulls
