### ISSUE TITLE
DeprecationWarnings with current release 1.9.0

### ISSUE THREAD

**Issue by sallner** [IdentityPython/JWTConnect-Python-CryptoJWT#157]
I use `cryptojwt = 1.8.3` and `cryptography = 42.0.5` and I get the following `DeprecationWarning`:

    def new_ec_key(crv, kid="", **kwargs):
>       _key = ec.generate_private_key(curve=NIST2SEC[crv], backend=default_backend())
E       cryptography.utils.CryptographyDeprecationWarning: Curve argument must be an instance of an EllipticCurve class. Did you pass a class by mistake? This will be an exception in a future version of cryptography.

As I try to get rid of `DeprecationWarnings` preemptively, I asked myself if there is the intention to change the behaviour in `cryptojwt` soon and how I could help with that. I already upgraded to the newest release `cryptojwt = 1.9.0`, but the warning is still there.

**Comment by jschlyter** [comment]
Yes, it seems like a bug. I'll look into it!

**Comment by jschlyter** [comment]
@sallner please try fix in #158

**Comment by jschlyter** [comment]
ping @sallner

**Comment by jschlyter** [comment]
[1.9.1](https://github.com/IdentityPython/JWTConnect-Python-CryptoJWT/releases/tag/v1.9.1) released
