### ISSUE TITLE
Wrong type in JWE_EC.dec_setup

### ISSUE THREAD

**Issue by vernans** [IdentityPython/JWTConnect-Python-CryptoJWT#159]
Hello cryptojwt team,
Thanks for your work, it usually works like a charm.
I found an issue in `cryptojwt.jwe.jwe_ec.JWE_EC.dec_setup`.

https://github.com/IdentityPython/JWTConnect-Python-CryptoJWT/blob/727bb9bff122a67e4e270330d990a7c1a1199664/src/cryptojwt/jwe/jwe_ec.py#L147

`apu` and `apv` are assigned `""` when they are declared. When there is no other value in the header for them subsequently `ecdh_derive_key` crashes because it's trying to concatenate these strings with bytes. I guess they should be assigned a `b""`.

As I know your time also doesn't grow on trees let me know if I can help you with providing a PR for that.

**Comment by jschlyter** [comment]
Please create a PR and I'll process it swiftly.
