### ISSUE TITLE
jwk.get_key(private=False) returns private key object

### ISSUE THREAD

**Issue by jschlyter** [IdentityPython/JWTConnect-Python-CryptoJWT#2]
It seems jwk.get_key(private=False) returns private key object. Shouldn't it return a public key one?

    import cryptojwt.jwk
    from cryptography.hazmat.backends import default_backend
    import cryptography.hazmat.primitives.asymmetric.ec as ec
    import cryptography.hazmat.primitives.asymmetric.rsa as rsa
    
    ec_key = ec.generate_private_key(cryptojwt.jwk.NIST2SEC['P-256'], default_backend())
    ec_jwk = cryptojwt.jwk.ECKey(key=ec_key, kid='test')
    print(type(ec_jwk.get_key(alg='EC', private=False)))
    
    rsa_key = rsa.generate_private_key(3, 2048, default_backend())
    rsa_jwk = cryptojwt.jwk.RSAKey(key=rsa_key, kid='test')
    print(type(rsa_jwk.get_key(alg='RSA', private=False)))

**Comment by jschlyter** [comment]
Workaround:

    jwk = cryptojwt.jwk.key_from_jwk_dict(jwk.serialize(private=False), private=False)

**Comment by jschlyter** [comment]
One could of course argue that the key object is to be considered opaque and not be messed around with. @rohe, your call :-)

**Comment by rohe** [comment]
If you specify that you don't want the private key you must get the public one.
That's a bug.

**Comment by jschlyter** [comment]
Want patch?

**Comment by jschlyter** [comment]
Closing with PR https://github.com/IdentityPython/cryptojwt/pull/5
