### ISSUE TITLE
How to create 'cookie_sign_jwks.json'

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/JWTConnect-Python-CryptoJWT#23]
Using this:

````
from cryptojwt.jwk.hmac import SYMKey
from cryptojwt.jws.jws import JWS

key = SYMKey(key=b'My hollow echo chamber', 
             kid='cookie',
             use='sig')
print(json.dumps(key.serialize(),indent=2))
````

I get 
````
{
  "kid": "cookie",
  "k": "TXkgaG9sbG93IGVjaG8gY2hhbWJlcg",
  "use": "sig",
  "kty": "oct"
}
````

But if I use this as cookie_sign_jwks.json in oidc-op I get and exception when RP made a request. The exception is:

````
oidcmsg.exception.MissingSigningKey: alg=RS256
````

What I'm doing wrong?

**Comment by rohe** [comment]
alg=RS256 means you need a RSA key. A symmetric key is not going to help.

**Comment by rohe** [comment]
Also, you need to be clear about the difference between a JWKS and a JWK.
What you got when you serialised the key above is a JWK.
I've tried to reflect this in the file names I use. 
Hence `cookie_sign_jwks.json` looks like it pointed to a JWKS. When in fact I think it expects a JWK. The name I have in conf.yaml is `cookie_sign_jwk.json`.

**Comment by peppelinux** [comment]
Ok Roland, I'll fix this semantics.
Now I have to deal, for documentation and base knowlededge, with the scenario whithin a system administrator that have to create his AS/OP and RP test platforms.

He have to deal with jwk(s) files.
As we seen in this [issue](https://github.com/rohe/oidc-op/issues/5#issuecomment-526119472) the best way is the automatic key creation but it doesn't work for every jwks file definition. In addition to this ww should need of some basic instructions to create jwks file by our own.

In this issue I'm looking for a way to create a `cookie_sign_jwk.json`.
Certainly you have the solution already in your hands :) I'll just get this information from you before putting this in the oidc-op Readme.

Probably this issue is also related to this https://github.com/rohe/oidc-op/issues/7 that I get in a different moment (after the login process). So I think that some jwks is inconsistent or completely wrong...

**Comment by peppelinux** [comment]
This issue can be closed now, It regards the jwk files.
Letting them to be autocreated by `cryptojwt.key_jar.init_key_jar` solves the problem.

I'd have to have a better look into init_key_jar to built a safe procedure to produce and verify jwk by hands. Thank you @rohe, a spell in the right moment always do the difference!
