### ISSUE TITLE
[Documentation] CryptoJWT is only supported in python3.6 and newer

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/JWTConnect-Python-CryptoJWT#24]
Because of f-strings
````
Traceback (most recent call last):
  File "~/DEV3/OIDC-Project/env/bin/jwkgen", line 6, in <module>
    from cryptojwt.tools.keygen import main
  File "~/DEV3/OIDC-Project/env/lib/python3.5/site-packages/cryptojwt/tools/keygen.py", line 46
    help=f'RSA public key exponent (default {DEFAULT_RSA_EXP})',
                                                              ^
SyntaxError: invalid syntax
````

I'll try to put in a PR a python badge into the Readme

**Comment by rohe** [comment]
You think we should include 3.5 ?

**Comment by peppelinux** [comment]
> You think we should include 3.5 ?

If oidcservice would be implemented into SATOSA -> yes
I dugged into source code and the only 3.6 dependencies are those f-strings in argparse, probably we could do without it.

**Comment by rohe** [comment]
Definitely! So, do you or I remove the f-strings ?

**Comment by peppelinux** [comment]
I'm doing it, I'll put it in the pending PR with fixed badges

**Comment by rohe** [comment]
Too fast for you :-) Already approved that !

**Comment by peppelinux** [comment]
> Too fast for you :-) Already approved that !
when i grow up i wanna be like you!

Here
https://github.com/openid/JWTConnect-Python-CryptoJWT/pull/26

**Comment by jschlyter** [comment]
I believe this can be closed?

**Comment by peppelinux** [comment]
Yes
