### ISSUE TITLE
DSASigner signer/verifier uses ASN.1 (X9.62)

### ISSUE THREAD

**Issue by jschlyter** [IdentityPython/JWTConnect-Python-CryptoJWT#3]
The DSASigner encodes signatures in ASN.1 (X9.62), but JWS expects a plain r||s encoding. DSASigner.sign and DSASigner.verify needs to use [cryptography.hazmat.primitives.asymmetric.utils.decode_dss_signature](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/utils/#cryptography.hazmat.primitives.asymmetric.utils.decode_dss_signature) and [cryptography.hazmat.primitives.asymmetric.utils.encode_dss_signature](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/utils/#cryptography.hazmat.primitives.asymmetric.utils.encode_dss_signature).

**Comment by jschlyter** [comment]
Is there a `cryptography` version of `Cryptodome.Util.number.long_to_bytes`?

**Comment by rohe** [comment]
No

**Comment by jschlyter** [comment]
Preliminary fix in https://github.com/jschlyter/cryptojwt/tree/fix_dsasigner

**Comment by jschlyter** [comment]
PR in https://github.com/IdentityPython/cryptojwt/pull/4

**Comment by jschlyter** [comment]
Closing this issue, handle in PR.
