### ISSUE TITLE
ECKey constructor's "key" argument is replacing the argument "x5c" on AsymmetricKey constructor

### ISSUE THREAD

**Issue by jpslopes** [IdentityPython/JWTConnect-Python-CryptoJWT#30]
Hello, I tried to load a JWKS from an url source using the KeyBundle and it gave the following error:
`Key bundle update failed: __init__() got multiple values for argument 'x5c'`.

After debugging the code I noticed that the problem was in the **ECKey** constructor's argument **key**:
 ```
def __init__(self, kty="EC", alg="", use="", kid="", key=None,
              crv="", x="", y="", d="", **kwargs):
    AsymmetricKey.__init__(self, kty, alg, use, kid, key, **kwargs)
```

As we can see in the **AsymmetricKey** constructor, it is not expecting the argument **key**, but instead the **x5c**:
```
def __init__(self, kty="oct", alg="", use="", kid="",  x5c=None, x5t="",
             x5u="", k="", pub_key=None, priv_key=None, **kwargs):
    JWK.__init__(self, kty, alg, use, kid, x5c, x5t, x5u, **kwargs)
```
So, the **ECKey** constructor is passing the argument **key** to **AsymmetricKey** as if it is the argument **x5c**.

The solution is simple: as the key argument is never used, it is only necessary to remove `key=None` from **ECKey** constructor and `key` from `AsymmetricKey.__init__(self, kty, alg, use, kid, key, **kwargs)`:
 ```
def __init__(self, kty="EC", alg="", use="", kid="",
              crv="", x="", y="", d="", **kwargs):
    AsymmetricKey.__init__(self, kty, alg, use, kid, **kwargs)
```

Thanks

**Comment by rohe** [comment]
Thanks !

**Comment by jpslopes** [comment]
Do you have any idea when this fix will be released?

**Comment by jpslopes** [comment]
Thanks!
