### ISSUE TITLE
Setting only public_path in init_key_jar fails

### ISSUE THREAD

**Issue by angelakis** [IdentityPython/JWTConnect-Python-CryptoJWT#36]
It tries to write in private_path which is None.

https://github.com/IdentityPython/JWTConnect-Python-CryptoJWT/blob/6f8dbb1e0003a247f791dad46ff4e2a2ec661167/src/cryptojwt/key_jar.py#L841

**Comment by rohe** [comment]
Cut and paste error.

**Comment by rohe** [comment]
Pushed a fix.
