### ISSUE TITLE
kty is case sensitive

### ISSUE THREAD

**Issue by jschlyter** [IdentityPython/JWTConnect-Python-CryptoJWT#37]
In 689e0030dde030efd13cbc677dbc36a95d7ea78a, `alg2keytype` is changed so it returns `OCT` instead of `oct` although RFC 7517 states that the "kty" value is a case-sensitive string.

Should the return value of `alg2keytype` be considered a valid kty?

**Comment by jschlyter** [comment]
This change broke a lot of code here :-)

**Comment by rohe** [comment]
OK, I'll retrace.

**Comment by rohe** [comment]
But, using Postel's saying I think it's reasonable that we allow case insensitive matching.

**Comment by jschlyter** [comment]
Agree, we should always emit lowercase for `oct` and compare case sensitive. It is strange however, that EC and RSA is specified in uppercase and oct in lowercase.

**Comment by rohe** [comment]
It's very strange. Probably because of some arcane historic reason :-)

**Comment by rohe** [comment]
Pushed 0.8.1 can you check it and if it's OK I'll release it on pypi.

**Comment by jschlyter** [comment]
Works fine!
