### ISSUE TITLE
Python 3.5 not supported?

### ISSUE THREAD

**Issue by davidkhess** [IdentityPython/JWTConnect-Python-CryptoJWT#74]
The setup.py indicates Python 3.5 is supported but `cryptojwt/jwk/__init__.py` is using type annotation syntax that was introduced in Python 3.6:

```
  File ".../lib/python3.5/site-packages/cryptojwt/jwk/__init__.py", line 27
    longs: List[str] = []
         ^
SyntaxError: invalid syntax
```

Is Python 3.5 supported?

**Comment by rohe** [comment]
No !
Will change setup.py.

**Comment by peppelinux** [comment]
here's
https://github.com/IdentityPython/JWTConnect-Python-CryptoJWT/commit/a0e26ce2d1473ff3bcd780a90b0993e1d0492815
