### ISSUE TITLE
Time skew handling

### ISSUE THREAD

**Issue by jschlyter** [IdentityPython/JWTConnect-Python-CryptoJWT#75]
How is time skew handling intended to be handled for JWTs? I can see that `class JWT` has a `skew` parameter, but it is not used anywhere? I basically want to allow JWTs with a small skew in `nbf` in order to handle minor time differences between services.

**Comment by rohe** [comment]
I put it in there because I knew that sooner or later I would need it but that was as far as I got.

**Comment by jschlyter** [comment]
Do we want `unpack()` to be able to verify `nbf` and `exp` as an option?

**Comment by rohe** [comment]
So, the original idea was that JWT was supposed to be a general JWT class with a minimal set of methods and then you where to use a more specialised JWT class (like oidcmsg.oidc.IdToken, a special Google Token or what have you) which would handle verification. That's where verify_profile() comes in.

**Comment by jschlyter** [comment]
Makes sense!
