### ISSUE TITLE
Remove RSA1_5 from Documentation example

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/JWTConnect-Python-CryptoJWT#88]
As RSA 1.5 has been deprecated here:
https://github.com/IdentityPython/JWTConnect-Python-CryptoJWT/pull/86

we should update the examples in the Documentation with another algorithm, eg: "RSA-OAEP" or any other.

**Comment by rohe** [comment]
Agree, we should replace RSA1_5 with RSA-OAEP where appropriate.

**Comment by rohe** [comment]
A quick search also reveals RSA1_5 in a couple of tests and in src/cryptojwt/jwt.py and src/cryptojwt/jwk/wrap.py .
We can replace i tests but changing jwt.py and wrap.py is trickier. That could easily be a breaking change.

**Comment by peppelinux** [comment]
> A quick search also reveals RSA1_5 in a couple of tests and in src/cryptojwt/jwt.py and src/cryptojwt/jwk/wrap.py .
> We can replace i tests but changing jwt.py and wrap.py is trickier. That could easily be a breaking change.

@jschlyter is this intended to be closed or do we have to reopen until we fix what @rohe exposed in this thread?
Or instead open another Issue for that

**Comment by jschlyter** [comment]
@peppelinux I suggest we create a new issue for the general cleanup, ok?
