### ISSUE TITLE
RSA1_5 cleanup

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/JWTConnect-Python-CryptoJWT#90]
as @rohe exposed in https://github.com/IdentityPython/JWTConnect-Python-CryptoJWT/issues/88#issuecomment-845784638

A quick search also reveals RSA1_5 in a couple of tests and in src/cryptojwt/jwt.py and src/cryptojwt/jwk/wrap.py .
We can replace i tests but changing jwt.py and wrap.py is trickier. That could easily be a breaking change.

**Comment by peppelinux** [comment]
Could we consider that the following PRs
https://github.com/IdentityPython/JWTConnect-Python-CryptoJWT/pull/86
https://github.com/IdentityPython/JWTConnect-Python-CryptoJWT/pull/89
closes this issue?

**Comment by rohe** [comment]
Yes !
